spring.application.name=credflow

spring.datasource.url=jdbc:mysql://localhost:3306/credflow?createDatabaseIfNotExist=true

spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.open-in-view=false
server.port=9091
springdoc.swagger-ui.path=/

jwt.secret=your-super-strong-and-long-random-secret-key-goes-here-at-least-256-bits
jwt.expiration.ms=86400000


# Spring Mail Configuration (Gmail Example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sit21it003@sairamtap.edu.in
spring.mail.password=kvxkbpkmbwemtlwt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true